# Generated by Django 4.0.5 on 2022-12-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumosComputacionales',
            fields=[
                ('nro_insumo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_insumo', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('marca', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
