# Generated by Django 4.0.5 on 2022-12-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsumosOficina',
            fields=[
                ('nro_article', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_article', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
