# Generated by Django 4.1.1 on 2022-11-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('numero_chasis', models.CharField(max_length=17, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=10)),
                ('ultima_revision', models.DateField()),
                ('proxima_revision', models.DateField()),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
